### ISSUE TITLE
`to_xml()` produces invalid datetimes.

### ISSUE THREAD

**Issue by MatteBailey** [tlambert03/ome-types#104]
We recently discovered that the `to_xml()` function provided by `ome-types` produces datetimes that look like `2016-03-11T10:23:44.925154UTC`, which violate the [XSD dateTime format](http://books.xmlschemata.org/relaxng/ch19-77049.html). Instead, the datetime in this case should be `2016-03-11T10:23:44.9251548Z`, which is what is in the source XML.

Steps to reproduce:
1. Extract `OverViewScan.ome.xml` from this ZIP: [OverViewScan.ome.xml.zip](https://github.com/tlambert03/ome-types/files/7042315/OverViewScan.ome.xml.zip)
2. Load that XML into `ome-types`, output it to XML, and try to load it again, like this:
```python
from pathlib import Path
from ome_types import from_xml, to_xml

if __name__ == '__main__':
    og_xml = Path("OverViewScan.ome.xml").read_text()
    ome = from_xml(og_xml)
    output_xml = to_xml(ome)
    from_xml(output_xml)
```
3. Receive the following error:
```
xmlschema.validators.exceptions.XMLSchemaDecodeError: failed validating '2016-03-11T10:23:44.925154UTC' with XsdAtomicBuiltin(name='xs:dateTime'):

Reason: attribute StartTime='2016-03-11T10:23:44.925154UTC': Invalid datetime string '2016-03-11T10:23:44.925154UTC' for <class 'elementpath.datatypes.datetime.DateTime10'>
```

Thanks for taking a look!

**Comment by tlambert03** [comment]
Thanks @MatteBailey.
can you tell me what version of `elementpath` and `xmlschema` you have installed?

**Comment by MatteBailey** [comment]
From running `pip list`, I get `elementpath 2.2.3` and `xmlschema 1.4.1`.
