### ISSUE TITLE
NotImplementedError: OMEPyramidStore

### ISSUE THREAD

**Issue by Nicholas-Schaub** [tlambert03/ome-types#125]
While reading xml from a czi file, we received this message:

```bash
NotImplementedError: Encountered a combination of schema element and data type that is not yet supported. Please submit a bug report with the information below:
    element: XsdElement(name='OME:OME', occurs=[1, 1])
    data type: <java class 'loci.formats.ome.OMEPyramidStore'>
```

We are in the process of replacing the `OmeXml.py` model with `ome_types`, and this error is a blocker for us adopting `ome_types` into our Bioformats utility.

**Comment by tlambert03** [comment]
thanks!  any chance you could post the XML here?

**Comment by Nicholas-Schaub** [comment]
Actually, I overlooked a part of the error message. I think this is a false flag. I'll do some investigating, and I'll close if this isn't an issue. Thanks for the quick responses.

**Comment by Nicholas-Schaub** [comment]
It was indeed a false flag. Things are fixed.

I don't know if you remember, but we had a meeting with the AICSImageIO people are we were going to implement bindings for our library in AICSImageIO. This is the first step to that, so hopefully we should have something by the end of the week.

**Comment by tlambert03** [comment]
I do remember!  good to see you here.  Does this also mean you're temporarily unblocked with regards to #108 as well?  or was that kind of a different issue with third-party schema stuff in your XML?

**Comment by Nicholas-Schaub** [comment]
Yes, I'm unblocked for now. I just saw the `NotImplementedError` and thought a class didn't get generated. Turns out I just needed to convert types. Now that I know, it should be smooth sailing from here.
