### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by Nicholas-Schaub** [tlambert03/ome-types#126]
We recently switch our `bfio` utility from `OmeXml.py` to `ome-types`. We spent a significant amount of time optimizing our OME Tiff reader/writer and OME Zarr reader/writers. However, one thing we have noticed is that our readers have slowed down by more than an order of magnitude after switching to `ome-types`.

I did some profiling, and for a 2048x2048 16-bit image, our read time from initial loading to data in memory went from 90ms to >3s. It looks like further analysis reveals that >95% of the time is being spent in `ome_types.schema.to_dict`. Specifically with how the schema is being parsed by `xmlschema`. I'll dump the profile in a separate comment so I don't take up too much space here.

This is a deal breaker for us with this kind of performance, but at the same time `ome_types` is clearly the best option in terms of properly processing OME XML. We can process terrabytes of data a day, so a 30x or more slowdown creates a significant problem, and maybe being a little more sloppy with metadata is okay as long as we can still parse it out properly.

I'm not willing to give up on ome-types though, so if you're open to a discussion about optimization, I am happy to contribute (either discussion or code).

The first sets of questions I have are:
1. How tightly integrated is `xmlschema` with the repository? Would it be easy or difficult to switch to something else?
2. Is it possible we could create a lighter weight xml parser or figure out a way to do lazy parsing? Maybe we could use some alternative to `xmlschema` when we are reasonably certain that the metadata will pass schema checks.

Based on what I've seen so far, it looks like all XML data is parsed to a dictionary and then passed to other things. So it at least seems possible to change over to something else as long as the input is xml and the output is dictionary that uses the parsing definitions found in `schema.OMEConverter`.

**Comment by tlambert03** [comment]
I suspect that this is mostly due to 1) validation (in addition to parsing) and performance of xmlschema itself.

1) for validation, see #108, where I think everyone agrees it would be nice to have a parser that pretty much doesn't validate at all... and just lets ignores stuff or lets errors happen elsewhere
2) for parsing... `xmlschema` isn't super tightly integrated... and I'd love to move to lxml which would significantly speed things up.  See https://github.com/tlambert03/ome-types/pull/103 for an example of stuff that I was doing to remove dependence on xmlschema in prep for lxml

mostly, I focused at first on correctness and API, but more than happy to dig (or have someone dig) into performance issues now.  It just hasn't really come up yet, so I suspect there's a lot of low hanging fruit

**Comment by Nicholas-Schaub** [comment]
Here is the profile I got from `to_dict`. I used an OME Tiff file that was converted from a czi file, and Zeiss likes to go crazy with the metadata.

Things to note:
1. Total script execution time was 25.2s
2. Units under `Time` are in microseconds
3. In the script, I load the same image twice. This means that the second call to `get_schema` should be cached since it's using `lru_cache`.

```bash

Timer unit: 1e-06 s

Total time: 25.2 s
Function: to_dict at line 225

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   225                                           @profile
   226                                           def to_dict(  # type: ignore
   227                                               xml: str,
   228                                               schema: Optional[xmlschema.XMLSchema] = None,
   229                                               converter: XMLSchemaConverter = OMEConverter,
   230                                               **kwargs,
   231                                           ) -> Dict[str, Any]:
   232         4    6583856.0 1645964.0     26.1      schema = schema or get_schema(xml)
   233         4   14872838.0 3718209.5     59.0      result = schema.to_dict(xml, converter=converter, **kwargs)
   234                                               # xmlschema doesn't provide usable access to mixed XML content, so we'll
   235                                               # fill the XMLAnnotation value attributes ourselves by re-parsing the XML
   236                                               # with ElementTree and using the Element objects as the values.
   237         2         10.0      5.0      0.0      tree = None
   238      4002       2405.0      0.6      0.0      for annotation in result.get("structured_annotations", []):
   239      4000       3331.0      0.8      0.0          if annotation["_type"] == "xml_annotation":
   240      4000       2182.0      0.5      0.0              if tree is None:
   241         2         38.0     19.0      0.0                  from io import StringIO
   242                                           
   243                                                           # determine if we're dealing with a raw XML string or a filepath
   244                                                           # very long XML strings will raise ValueError on Windows.
   245         2          2.0      1.0      0.0                  try:
   246         2       5104.0   2552.0      0.0                      _xml = xml if os.path.exists(xml) else StringIO(xml)
   247                                                           except ValueError:
   248                                                               _xml = StringIO(xml)
   249                                           
   250         2      16327.0   8163.5      0.1                  tree = ElementTree.parse(_xml)  # type: ignore
   251      4000       2198.0      0.5      0.0              aid = annotation["id"]
   252      4000    3705077.0    926.3     14.7              elt = tree.find(f".//{NS_OME}XMLAnnotation[@ID='{aid}']/{NS_OME}Value")
   253      4000       6648.0      1.7      0.0              annotation["value"] = elt
   254         2          1.0      0.5      0.0      return result```

**Comment by Nicholas-Schaub** [comment]
I did do even more digging than this, including doing some initial parsing using `lxml`, but even `xmlschema.to_dict` took up a considerable amount of the time.

Once you use `to_dict`, isn't it a dictionary? And do other parts of the code use `xmlschema` or is it only used in `schema.py`?

**Comment by Nicholas-Schaub** [comment]
Your point about Pydantic makes sense. I think I read that you're generating the pydantic classes based off the xml schema. So most validation checks are effectively carried out a second time by Pydantic, even if things like element ordering are not validated by Pydantic.

If you're open to this I think I'm going to work on this a bit. It seems like the key thing to make this work with the rest of the code is to make sure the output format is dict, mainly because that makes instantiating pydantic classes easier. So, I think rather than replacing the current version maybe a parallel lightweight version of `to_dict` that just parses the element tree into a dictionary makes sense?

**Comment by tlambert03** [comment]
correct, `xmlschema` is mostly used as a buildtime dependency to autogenerate the python code from the OME XML schema. at runtime, however, it is only used in `schema.py` and then only in (as mentioned above) a real **excess** of caution to first validate that the user's XML string conforms to the OME XML schema before converting it to a dict.  But then note that after that occurs, the python model itself will also perform some validation.

Long story short, we can use `lxml`  instead of `xmlschema` when parsing the input XML and converting it to a dict... and I would expect that to be _much_ faster.  Both due to the lack of xml validation, and due to the fact that `lxml` is just plain faster at parsing XML in the first place.

> If you're open to this I think I'm going to work on this a bit.

I would _looove_ that :)  I have long wanted this to be faster, just haven't had time or an immediate need.  I would encourage you to check out [this branch](https://github.com/tlambert03/ome-types/tree/lxml).  If I recall, it was reasonably close to working with lxml.  See the new [`from_xml` function](https://github.com/tlambert03/ome-types/blob/3e9b5fb241685564b92dc557b30d1c627da32abe/src/ome_types/_convenience.py#L8), which had a new `validate=False` param, and fell back to `lxml2dict`, which was [defined here](https://github.com/tlambert03/ome-types/blob/3e9b5fb241685564b92dc557b30d1c627da32abe/src/ome_types/util.py#L129).

I suspect a little bit more tweaking will be needed to make the dict pass as input to the pydantic model.  And I'd point you [here](https://github.com/tlambert03/ome-types/blob/b3942586d0a10e0f122fa2a1d3cea2df81ca7fce/src/ome_types/schema.py#L102-L146) for where those little hacks currently happen with the xmlschema importer.


This would be amazing to get across the finish line, so let me know if I can help

**Comment by Nicholas-Schaub** [comment]
This is how I get involved in too many things haha. I'll use that branch as a starting point. I'll also try to create a unit test to test...something. Either make sure the dictionaries we get from each method are equivalent or maybe just comparing `OME.to_json` or `OME.to_dict`, which should be a little more consistently structured.

**Comment by tlambert03** [comment]
> This is how I get involved in too many things haha.

you and me both :joy:  

Sounds like a great place to start.  Don't drive yourself nuts though.  If it's enjoyable and you keep feeling like you see the path forward, it would be great.  But if you start getting annoyed, lemme know.  I also do want this to work so could pick it up from there

**Comment by Nicholas-Schaub** [comment]
Too late. I'm already going nuts. I'll figure it out.

**Comment by Nicholas-Schaub** [comment]
I have it working on 50% of the test files, so still a few things to work out. However, now that I've dug around the code a bit, I think discussing what a final solution might look like is appropriate.

First, I noticed that there was a difference between the lxml result and the xmlschema result. It looks like there are additional flavor attributes that are added to the dictionary for the xmlschema result that are not present in the lxml result. These missing attributes do not appear to cause a problem with Pydantic classes. They are things like units for microscope bulbs and things like that.

Related to this, one of the things I played around with before opening the issue was validating with lxml. I think I'm going to add in lxml validation which will parse out the XML using schema. I suspect this will give a result closer to what xmlschema gives. It's only a couple more lines of code and the schema parsing doesn't seem to add much overhead (surprisingly).

Finally, the implementation. I think I see three types of parsing related to validation, so maybe we could have the `from_xml` have a `validation` keyword that takes three values:
`strict` - current xmlschema approach. Even if lxml can provide similar chema validation, I think it's good to keep this for a few releases in case there are bug reports for lxml.
`light` - use this to use lxml schema validation. This may be a misnomer since it might perform as strictly as xmlschema.
`off` - only parse with lxml without schema parsing, hope pydantic doesn't have problems.

Most of my work on this has been figuring out how it works. Finishing this off should go quickly now, assuming there are no surprises.

**Comment by tlambert03** [comment]
Sounds great!  i wonder if rather than having on validation param with `strict/light/off`, we might have two params: `converter` - a function that converts xml to dict (could be either xmlschema or lxml, or anything in the future) and `validate`, a boolean that determines whether the xml should be validated or not (still up to the converter to perform though).  Might be a bit more future proof if we come up with something even better than lxml?  Default would be `converter=lxml2dict, validate=False`.

**Comment by Nicholas-Schaub** [comment]
I guess thats true. Even with xmlschema, I don't think it's necessary to validate.

I think this is a good solution. Once I finish fixing some of these trailing issues I'll work on implementing these options. Right now I'm getting roughly a 6x performance boost using lxml versus xmlschema. That seems a bit slow to me, but I'm not going to optimize just yet. I think I see a number of areas that could be bogging this down outside of lxml, but I'll leave that for a subsequent PR.

**Comment by Nicholas-Schaub** [comment]
I have a "rough draft" of it ready.

It currently passes all unit tests for parsing the xml to a dictionary then passing to Pydantic. I added a new parameter to `test_from_xml` to test parsing with and without validation.

It currently defaults to `validate=True`. When I default to `validate=False`, it doesn't pass the roundtrip tests (yet).

I need to add in the lxml schema validation and the `converter` arg.

I don't think it will be ready for a PR until I add the validate parameter to all unit tests that use `from_xml` and they all pass. However, I thought I would share the code if you wanted to take a look. It is a little hacky, but not too bad. It needs some cleaning yet, but if you look at the logic and something doesn't make sense, I can try to change it or add in some comments.
https://github.com/Nicholas-Schaub/ome-types/blob/lxml/src/ome_types/util.py

**Comment by Nicholas-Schaub** [comment]
I've been able to parameterize all of the tests that use `from_xml` to use validation. There are now 240 tests, and all but 5 pass. I suspect the last 5 to fix might have to do with some of the exceptions you catch when encoding.

I couldn't help myself but do a little optimization. As I suspected, the biggest drain was regular expressions. I was able to compile and rewrite them a bit, and now we are getting a 12x speedup compared to the 6x speedup we had before. One thing i thought of that would likely improve performance globally (for both xmlschema and lxml) is to use attribute aliasing on Pydantic classes. Right now, a lot of time is spent converting camel case to snake case when parsing. What we could do instead is create attribute aliases so that when you initialize a pydantic class with `PlateRef=value` it would end up setting `plate_ref=value`. You could also access the attribute using either `object.PlateRef` or `object.plate_ref`. I don't know if that would break your system, but using aliasing would probably reduce the total amount of code you would have in the repo and improve performance. You would take an initial hit when loading the library, but you would reduce the time spent parsing.

Obviously not something to do for this PR, but possibly something to consider if it's feasible for performance. I use this kind of aliasing when creating Typescript-Python interfaces so that we can keep snake case in Python and camel case in Typescript.

**Comment by Nicholas-Schaub** [comment]
Also, the nice thing about aliasing is that you don't need to custom code the names. You can just create a generator.

https://pydantic-docs.helpmanual.io/usage/model_config/#alias-generator

**Comment by tlambert03** [comment]
> I was able to compile and rewrite them a bit, and now we are getting a 12x speedup compared to the 6x speedup we had before

my hero 🤩

> use attribute aliasing on Pydantic classes.

That sounds like a great idea!

**Comment by Nicholas-Schaub** [comment]
We handle such a large number of files from such a diversity of sources I just assume that if it fails your tests, then we are going to have a problem. I'm assuming that we might still have issues even with all your extensive testing. I know we have run into quite a few special cases in the past, but I really like how extensive your tests are.

I am resolving the final two and then I'll open a PR. I haven't gotten to profiling `to_xml` for our image writer, but I might want to take a look at the performance of that as well.

I'll open a separate issue for the Pydantic aliasing.

Another question I thought of: Both our library and AICImageIO have special catches for fixing common problems in metadata written by `OmeXml.py`. Are you interested or considered migrating their work into this repo so that if validation fails `ome-types` could make an attempt to fix it? I can point you to some code if you want to take a look. Basically, we have a boolean value you can set to try and fix errors, and if it's unset then it will throw the standard validation errors.

**Comment by Nicholas-Schaub** [comment]
I did some digging on those last two errors and I'm throwing in the towel because I don't think they are significant. Basically, when you parse data using schema validation it adds in default values for units, and possibly some additional xml flavoring that I don't believe contribute to any meaningful differences. What I did for now is create a special test exception case.

I also ran benchmarks using pytest, and I think there might be some overhead associated with the tests that don't give you a real feel for how big of a difference there is between the two. So, what I did was just profile `from_xml` over ten runs. I switched the ordering of which gets called first in case there was some lazy loading startup times, and there really wasn't a meaningful difference. You can see below that lxml for the indicated test file runs in 0.256 ms where xmlschema.to_dict runs in 645ms.

I have to add in the different parsers and cleanup code then it should be good to go.

```bash
Timer unit: 1e-06 s

Total time: 6.47677 s
File: /home/schaubnj/anaconda3/envs/py39/lib/python3.9/site-packages/ome_types/_convenience.py
Function: from_xml at line 8

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     8                                           @profile
     9                                           def from_xml(xml: Union[Path, str, bytes], validate=True) -> OME:  # type: ignore
    10                                               """Generate OME metadata object from XML string or path.
    11                                           
    12                                               Parameters
    13                                               ----------
    14                                               xml : Union[Path, str]
    15                                                   Path to an XML file, or literal XML string.
    16                                           
    17                                               Returns
    18                                               -------
    19                                               ome: ome_types.model.ome.OME
    20                                                   ome_types.OME metadata object
    21                                               """
    22        20         21.0      1.1      0.0      if validate:
    23        10         55.0      5.5      0.0          from .schema import to_dict
    24                                           
    25        10         41.0      4.1      0.0          xml = os.fspath(xml)
    26        10          6.0      0.6      0.0          if isinstance(xml, bytes):
    27                                                       xml = xml.decode("utf-8")
    28        10    6453479.0 645347.9     99.6          d = to_dict(xml)
    29        50         52.0      1.0      0.0          for key in list(d.keys()):
    30        40         29.0      0.7      0.0              if key.startswith(("xml", "xsi")):
    31        30         23.0      0.8      0.0                  d.pop(key)
    32                                               else:
    33        10         86.0      8.6      0.0          from .util import lxml2dict
    34                                           
    35        10       2561.0    256.1      0.0          d = lxml2dict(xml)
    36        20      20422.0   1021.1      0.3      return OME(**d)  # type: ignore
```
