### ISSUE TITLE
Performance: Use Pydantic aliasing to handle snake and camel case

### ISSUE THREAD

**Issue by Nicholas-Schaub** [tlambert03/ome-types#128]
A significant amount of time is spent during parsing converting from camel case to snake case using regular expressions. An alternative to this is to use Pydantics aliasing feature, which allows mapping of multiple names to one attribute. Using aliasing, all camel case element names could be mapped to their snake case counterparts in Pydantic classes. This would lead to a performance hit when loading the Pydantic classes. However, once this is done Pydantic will directly map all camel case element names to snake case names, avoiding subsequent hits to performance when trying to map camel case to snake case. Driving the hit to performance on class loading rather than parsing is ideal for situations when parsing happens multiple times in the same Python session.

To implement this, the way Pydantic classes are generated would have to be modified to 1) include attribute aliasing code and 2) setting the configuration such that Pydantic classes can set values using attribute aliases. First, rather than converting to snake case when the model classes are generated, keep the original model attribute names and include the following to `class Config` under the `OMETypes` class.

```python
class Config:

    allow_population_by_field_name = True    # This allows you to you use CamelCase when initializing a class
    alias_generator = camel_to_snake         # This maps CamelCase to snake_case when the class is loaded
```

Then, include the `camel_to_snake` function currently in the `ome_autogen.py` to `_base_type.py`. This will cause all inheriting classes to auto-generate aliases.

The benefit to using aliases is that Pydantic uses aliases by default when serializing. So even if you initialize a class using `PlateRef` as a keyword argument, when using `dict()` or `json()` methods, the fields will show up as `plate_ref`.

This conversion may be made a little more complicated by the use of plural name conversions, but this just might result is a slightly more complex `camel_to_snake` function, which means even less burden on the parser to parse out names properly.

Using aliasing should help to simply parsing logic and reduce the amount of code in addition to helping to globally improve performance for both `schema.to_dict` and `lxml2dict`.

**Comment by Nicholas-Schaub** [comment]
https://pydantic-docs.helpmanual.io/usage/model_config/#alias-generator

**Comment by tlambert03** [comment]
#205 significantly improves performance with pydantic2 support:
<img width="626" alt="Screen Shot 2023-07-13 at 5 50 16 PM" src="https://github.com/tlambert03/ome-types/assets/1609449/7932581c-aae8-4ae8-b41a-41f21d7bc237">
