### ISSUE TITLE
Whole Slide OMETIFF pyramid levels

### ISSUE THREAD

**Issue by rjesud** [tlambert03/ome-types#137]
Hi, Thanks for creating such a useful tool!

I cannot seem to find metadata corresponding to the number of subresolution pyramid levels for whole slide OMETIFFs. Does the ometypes API support this query?

r

**Comment by tlambert03** [comment]
I admit ignorance!
@joshmoore, where would that data live?  Is that something reflected in the OME data model?  or something that requires a schema on top of the core model?

**Comment by joshmoore** [comment]
Hi @rjesud. The subresolutions levels are a feature of the underlying TIFF storage (and of the Zarr storage in [NGFF](https://ngff.openmicroscopy.org/)). https://github.com/cgohlke/tifffile will let you choose between the levels:

```
>>> baseimage = imread('temp.ome.tif')
>>> second_level = imread('temp.ome.tif', series=0, level=1)
>>> with TiffFile('temp.ome.tif') as tif:
...     baseimage = tif.series[0].asarray()
...     second_level = tif.series[0].levels[1].asarray()
```

`len(series[X].levels)` will give you the total number.

If you think there's a use case for having the resolution metadata in the model itself, do let us know. The downside would be the potential for the two values to get out of sync.

**Comment by rjesud** [comment]
@joshmoore Thanks for this solution! Conincidently, I am using tiffile for this particular workflow. I am actually using the zarr api to access specific channels and pyramid levels of a multi-channel IF OMETIFF WSI. 

```
>>> import zarr
>>> store = imread('temp.ome.tif', aszarr=True)
>>> z = zarr.open(store, mode='r')
```

I have a routine where I want to need the WSI pixel data as a downsampled array (very specific factor). So, I figured I would just load a pyramid level rather than loading a higher res array then downsampling. Before loading any arrays in memory, I wanted to know what pyramid levels are available (your solution now gives this to me) and also, what is their downsample factor. While I would hope every pyramid level is a factor of 2 scaling, I suppose this may not neccassarily be the case.

**Comment by joshmoore** [comment]
Hi @rjesud. It definitely need not be the case that all levels are a factor of 2 downscaled.

**Comment by tlambert03** [comment]
since I don't think there's any action items here for `ome-types`, I'm going to close this.  If I'm mistaken, please let me know and we can reopen!
