### ISSUE TITLE
Can't read XMLAnnotations with lxml

### ISSUE THREAD

**Issue by S73ph4n** [tlambert03/ome-types#147]
Hi,
Using tifffile and ome-type, I construct a OME-TIFF containing, among other things, an XMLAnnotation.
The part of my code where I make the annotation looks like this :

```
xml_ann = ome_types.model.XMLAnnotation(
                    description="Some description",
                    value='<Data><Params A="1" B="2" C="3"/></Data>',
                )
metadata.structured_annotations.append(xml_ann)
```

Then, when I open that file with ome-types, using xmlschema as a parser :
`metadata = ome_types.from_tiff(path_out, parser='xmlschema')`
I get this, which is the expected behaviour :
![image](https://user-images.githubusercontent.com/1709064/191002324-42103782-995f-4096-b3cc-9837930d262d.png)

But, when I use lxml, I get an empty element :
`metadata = ome_types.from_tiff(path_out, parser='lxml')`

![image](https://user-images.githubusercontent.com/1709064/191003720-f3d385f7-52a3-46e8-8c26-d204d19b6068.png)

Interestingly, this only happens when I include a `description` in the XMLAnnotation. If I just do `xml_ann = ome_types.model.XMLAnnotation(value='<Data><Params A="1" B="2" C="3"/></Data>')` , I get the correct behaviour when reading it with either parser.

Versions : 
- ome-types : 0.3.1
- lxml : 4.8.0

**Comment by tlambert03** [comment]
@Nicholas-Schaub  and @jmuhlich 

would either of you be able to take a look at this, you each wrote the corresponding parsers and know about them more than I do.  Here's what I've determined so far.

First, a failing test (and whether the test itself is asserting the proper behavior is up for discussion...)  it's just asserting the current xmlschema behavior which is what @S73ph4n  was expecting.

```python
from ome_types.model import OME, XMLAnnotation
from ome_types import from_xml
import pytest


@pytest.mark.parametrize("parser", ("xmlschema", "lxml"))
def test_xml_annotation(parser: str) -> None:
    data_xml = '<Data><Params A="1" B="2" C="3"/></Data>'
    s = XMLAnnotation(description="Some description", value=data_xml)
    ome = OME(structured_annotations=[s])

    expected = list(s.value)[0].items()
    assert expected == [("A", "1"), ("B", "2"), ("C", "3")]

    new_anno = from_xml(ome.to_xml(), parser=parser).structured_annotations

    assert len(new_anno) == 1
    xml_anno = new_anno[0]
    assert isinstance(xml_anno, XMLAnnotation)
    assert xml_anno.value[0].items() == expected
```

Note that the XML output from `ome.to_xml()` looks like this:

```xml
<OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-06 http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd">
    <StructuredAnnotations>
        <XMLAnnotation ID="Annotation:2">
            <Description>Some description</Description>
            <Value><Params A="1" B="2" C="3"/></Value>
        </XMLAnnotation>
    </StructuredAnnotations>
</OME>
```

and from what I can tell the key difference is that [in this section of the xmlschema parser](https://github.com/tlambert03/ome-types/blob/74a3d22fa16c356c2162b472bd8cbb36f76ae3ae/src/ome_types/_xmlschema.py#L123-L131) the "result" will look like this:
```python
[
        {
            'id': 'Annotation:1',
            'description': 'Some description',
            'value': {'Params': [{'A': '1', 'B': '2', 'C': '3'}]},
            '_type': 'xml_annotation'
        }
]
```

whereas in the lxml parser, it will look like this (note the difference in the value)

```python
{
    "id": "Annotation:2",
    "description": "Some description",
    "value": b'<Description xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Some description</Description>\n            ',
    "_type": "xml_annotation",
}
```

It's conceivable that the "successful" behavior of the xmlschema parser was accidental, or that the behavior is unexpected, but I'm not sure and would appreciate your inputs.

thanks!

**Comment by tlambert03** [comment]
i don't think this is going to be relevant with the new release (ome-types was rewritten to use xsdata for most of the parsing, so the lxml parser that had this bug isn't used anymore)
