### ISSUE TITLE
Unable to not speciy Channel.Color

### ISSUE THREAD

**Issue by folterj** [tlambert03/ome-types#163]
Unable to not speciy Image->Pixel->Channel->Color
Not specifying it will create a default value of -1, which will be interpreted by QuPath/Bioformats as white.
If you have 3 separate channels without color specification QuPath/Bioformats will interpret it as RGB fine, but with color=-1 it will have 3 white channels.

Creating Channel() without color results in default color=-1. setting color=None results in an error as internally it's cast to int.
I would like the ability to create a Channel without color parameter in the resulting OME xml.

**Comment by tlambert03** [comment]
Thanks @folterj ... I agree.  The default behavior is *supposed* to be that unset fields are not written out to the XML.  Looks like this is due to the way the default value is set on the `Channel.color` field (it erroneously things it's *always* set when no value is provided)
