### ISSUE TITLE
schema caching needs xmlschema version

### ISSUE THREAD

**Issue by tlambert03** [tlambert03/ome-types#19]
just so I don't forget to fix it: when testing #17 locally a few tests failed that weren't testing on CI, so I updated xmlschema to check... and they _all_ failed.  I realized that it was ultimately due to the pickled schema cache being stale.  So that cache key should minimally have the xmlschema version in it, but maybe we don't cache at all.

**Comment by jmuhlich** [comment]
1. We should grab the .xsd and include it with the generated python code, then just load that. That thing isn't changing so no sense in fetching it from a remote server every run. (This usually takes less than a second but it also requires a network connection)
2. The schema parse takes over 2 seconds on my machine which I agree isn't great, but the hassle of managing the cache may not be worth it as you're also realizing...

**Comment by jmuhlich** [comment]
Remember there are only 2 truly hard problems in computer science: Naming things, cache invalidation, and off-by-one errors.

**Comment by tlambert03** [comment]
that's hilarious.

**Comment by tlambert03** [comment]
sounds good.  I'll add the xsd to source.  I think i'll leave the caching in there for now, but include the xmlschema version string and ome-types version in the key.  That should cover everything but development woes, and we can deal with that ourselves

**Comment by jmuhlich** [comment]
Actually the schema parse only takes 1 second. I was accidentally timing it loading from the URL rather than a local file. I don't know if 1 second is even worth all the hassles of caching. (e.g. if it's a binary wheel install, that path doesn't even exist for writing a file to and you need to find somewhere else...)
