### ISSUE TITLE
Use native numpy types for pixel data types

### ISSUE THREAD

**Issue by tlambert03** [tlambert03/ome-types#2]
from @jmuhlich
Figure out how to use numpy dtypes instead of a separate enum for pixel data types.  Preferably with numpy as an optional dependency.

**Comment by tlambert03** [comment]
@jmuhlich, curious how you think about this now...  If we don't want to depend on numpy, we can use string keys from `np.sctypeDict`... but what exactly is our goal here?  is it about our internal representation?  or the format(s) we accept?

There's a real possibility for confusion here since the OME `PixelType.FLOAT` corresponds to `np.float32`, while `np.float` corresponds to `PixelType.DOUBLE` ... same with complex numbers.  We would of course, need to convert back to OME world when writing to XML...

**Comment by jmuhlich** [comment]
What about the confusion issue? I think mapping to and from the numpy dtype strings would still be very useful.

**Comment by jmuhlich** [comment]
To clarify: I’m not suggesting we pull in numpy as a dependency, just adapt the values for this field to align with numpy nomenclature.
