### ISSUE TITLE
AttributeError with freshly released `xsdata==24.2`

### ISSUE THREAD

**Issue by m-albert** [tlambert03/ome-types#242]
Hi, thanks for your work here!

I just wanted to leave a quick report here of an error I encountered after installing `aicsimageio` in a fresh environment. It seems that `ome_types` doesn't like `xsdata==24.2` which was released yesterday 😅.

Here's how to reproduce the error:

Make sure to have `xsdata==24.2` and
```
`python -m ome_types`
```

<details>
<summary>Traceback</summary>

Traceback (most recent call last):
  File "/Users/malbert/mambaforge/envs/aicsimageio/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/malbert/mambaforge/envs/aicsimageio/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/malbert/mambaforge/envs/aicsimageio/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/malbert/mambaforge/envs/aicsimageio/lib/python3.10/site-packages/ome_types/__init__.py", line 17, in <module>
    from ome_types._conversion import from_tiff, from_xml, to_dict, to_xml, validate_xml
  File "/Users/malbert/mambaforge/envs/aicsimageio/lib/python3.10/site-packages/ome_types/_conversion.py", line 16, in <module>
    from xsdata_pydantic_basemodel.bindings import (
  File "/Users/malbert/mambaforge/envs/aicsimageio/lib/python3.10/site-packages/xsdata_pydantic_basemodel/bindings.py", line 32, in <module>
    class SerializerConfig(config.SerializerConfig):
  File "/Users/malbert/mambaforge/envs/aicsimageio/lib/python3.10/site-packages/xsdata_pydantic_basemodel/bindings.py", line 35, in SerializerConfig
    *config.SerializerConfig.__slots__,
AttributeError: type object 'SerializerConfig' has no attribute '__slots__'. Did you mean: '__class__'?

</details>

<details>
<summary>pip list</summary>
Package                    Version
-------------------------- ---------
aicsimageio                4.14.0
aiobotocore                2.5.4
aiohttp                    3.9.3
aioitertools               0.11.0
aiosignal                  1.3.1
annotated-types            0.6.0
asciitree                  0.3.3
asttokens                  2.4.1
async-timeout              4.0.3
attrs                      23.2.0
botocore                   1.31.17
certifi                    2024.2.2
charset-normalizer         3.3.2
click                      8.1.7
cloudpickle                3.0.0
dask                       2024.2.0
decorator                  5.1.1
distributed                2024.2.0
elementpath                4.3.0
exceptiongroup             1.2.0
executing                  2.0.1
fasteners                  0.19
frozenlist                 1.4.1
fsspec                     2023.6.0
idna                       3.6
imagecodecs                2024.1.1
imageio                    2.34.0
importlib-metadata         7.0.1
ipython                    8.21.0
jedi                       0.19.1
Jinja2                     3.1.3
jmespath                   1.0.1
lazy_loader                0.3
locket                     1.0.0
lxml                       4.9.4
MarkupSafe                 2.1.5
matplotlib-inline          0.1.6
msgpack                    1.0.7
multidict                  6.0.5
networkx                   3.2.1
numcodecs                  0.12.1
numpy                      1.26.4
ome-types                  0.4.5
ome-zarr                   0.8.3
packaging                  23.2
pandas                     2.2.0
parso                      0.8.3
partd                      1.4.1
pexpect                    4.9.0
pillow                     10.2.0
pip                        24.0
prompt-toolkit             3.0.43
psutil                     5.9.8
ptyprocess                 0.7.0
pure-eval                  0.2.2
pydantic                   1.10.13
pydantic-compat            0.1.2
pydantic_core              2.16.2
Pygments                   2.17.2
python-dateutil            2.8.2
pytz                       2024.1
PyYAML                     6.0.1
requests                   2.31.0
resource-backed-dask-array 0.1.0
s3fs                       2023.6.0
scikit-image               0.22.0
scipy                      1.12.0
setuptools                 69.0.3
six                        1.16.0
sortedcontainers           2.4.0
stack-data                 0.6.3
tblib                      3.0.0
tifffile                   2023.2.28
toolz                      0.12.1
tornado                    6.4
traitlets                  5.14.1
typing_extensions          4.9.0
tzdata                     2024.1
urllib3                    1.26.18
wcwidth                    0.2.13
wheel                      0.42.0
wrapt                      1.16.0
xarray                     2024.1.1
xmlschema                  3.0.1
xsdata                     24.2
yarl                       1.9.4
zarr                       2.15.0
zict                       3.0.0
zipp                       3.17.0
</details>

Downgrading `xsdata` to 24.1 resolves the problem.

**Comment by m-albert** [comment]
(What a fitting associated issue number 😁)

**Comment by tlambert03** [comment]
Thanks @m-albert!
I'll have a look tomorrow or the next day and release a fix.

> (What a fitting associated issue number 😁)

🤯

**Comment by m-albert** [comment]
Wow, thanks for such a quick fix @tlambert03 🚀

**Comment by tlambert03** [comment]
no problem, thanks again for reporting.  will release shortly
