### ISSUE TITLE
Appending elements to an OME object

### ISSUE THREAD

**Issue by phisanti** [tlambert03/ome-types#248]
I am working with images that come with lots of metadata, and we would like to preserve it all when we move from 
*.nd2 to *.ome.tiff. I have find a way to append extra information into the main OME object:
```python
import ome_types
from ome_types.model import MapAnnotation, Map
from ome_types.model.map import M
ome_test = ome_types.OME()

my_dict = data = {
            'uiWidth': '1608',
            'uiWidthBytes': '3216',
            'uiHeight': '1608',
            'uiComp': '1',
            'uiBpcInMemory': '16',
            'uiBpcSignificant': '12',
            'uiSequenceCount': '9',
            'uiTileWidth': '1608',
            'uiTileHeight': '1608',
            'eCompression': '2',
            'dCompressionParam': '0.0',
            'ePixelType': '1'
}

def dict2ome(metadata: dict) -> MapAnnotation:
    """Converts metadata dictionary to OME MapAnnotation"""

    map_annotation = MapAnnotation(
        value=Map(m=[M(k=_key, value=str(_value)) for _key, _value in metadata.items()])
    )

    return map_annotation

ome_extra = dict2ome(data)
ome_test.structured_annotations.extend([ome_extra])

ome_test.dict()
```

 but the result does not look ideal:
 ```
  'map_annotations': [{'description': None,
    'annotation_refs': [],
    'id': 'Annotation:0',
    'namespace': None,
    'annotator': None,
    'value': {'ms': [{'value': '1608', 'k': 'uiWidth'},
      {'value': '3216', 'k': 'uiWidthBytes'},
      {'value': '1608', 'k': 'uiHeight'},
      {'value': '1', 'k': 'uiComp'},
      {'value': '16', 'k': 'uiBpcInMemory'},
      {'value': '12', 'k': 'uiBpcSignificant'},
      {'value': '9', 'k': 'uiSequenceCount'},
      {'value': '1608', 'k': 'uiTileWidth'},
      {'value': '1608', 'k': 'uiTileHeight'},
      {'value': '2', 'k': 'eCompression'},
      {'value': '0.0', 'k': 'dCompressionParam'},
      {'value': '1', 'k': 'ePixelType'}]}} 
```

With this output, I have to iterate over all items until I find the right `k` to get the desired `value`. Therefore, I was wondering if you were aware of a more efficient method for appending elements to an OME object.

**Comment by tlambert03** [comment]
one slight issue in modeling an OME MapAnnotation as a python diction: I believe it's technically possible to have two `M` items in a `MapAnnotation` that have the same key (`K`).  so while the following is legal in OME, it would not be captured in the python dict:

```xml
<MapAnnotation >
    <Value>
        <M K="somekey">someval</M>
        <M K="somekey">someval</M>
        <M K="somekey">someval</M>
    </Value>
</MapAnnotation>
```

**Comment by phisanti** [comment]
Yeah, that looks really what I needed. So What I am doing at the moment is to add the "unstructured metadata" from the nd2 files in the OME object, so maybe I could add an OME section called "unstructured metadata and then append the `MapAnnotation` object.

**Comment by tlambert03** [comment]
I'll cut a new release today. You could try installing from GitHub if you're in a hurry to get started :) but it'll be up shortly
