### ISSUE TITLE
ome-types.readthedoc - attribute tiff_data in Pixels

### ISSUE THREAD

**Issue by rmassei** [tlambert03/ome-types#255]
Hi @tlambert03 ,
I noticided that for "Pixels" the attribure name "tiff_data" is not working and lead to the error:

> sys:1: UserWarning: Unrecognized fields for type <class 'ome_types._autogenerated.ome_2016_06.pixels.Pixels'>: {'tiff_data'}

However, it seems to work when the attribute name is "tiff_data_blocks".

**Readthedocs issue:**

- [ ] Fix the "readthedocs" for the "pluralized" names in the schema

**Comment by tlambert03** [comment]
ah, good catch.  Actually this is going to be true for all of the "pluralized" names in the schema.  So yes, readthedocs need to be fixed, which means that actually the (autogenerated) docstrings themselves need to be fixed... making it a bit more complicated.  Thanks for the heads up.  will fix xoon

**Comment by rmassei** [comment]
No problem, it is nice to contribute to ome-types :)
I will just add a task list to the issue to keep it tracked.

**Comment by tlambert03** [comment]
Fixed now, thanks for reporting!
