### ISSUE TITLE
xsd:list not handled in code generation

### ISSUE THREAD

**Issue by jmuhlich** [tlambert03/ome-types#35]
Elements defined as lists are skipped over during code generation. For example Experiment/Type:

```xml
<xsd:attribute name="Type" use="optional">
  ...
  <xsd:simpleType>
    <xsd:list>
      <xsd:simpleType>
        <xsd:restriction base="xsd:string">
          <xsd:enumeration value="FP"/>
          <xsd:enumeration value="FRET"/>
          ...   
        </xsd:restriction>
      </xsd:simpleType>
    </xsd:list>
  </xsd:simpleType>
</xsd:attribute>
```
The generated code ends up with `type = None` for that field, and no corresponding enum is produced.

Schemas can define `list`s containing any type, but the OME schema only has two cases: Experiment/Type and MicrobeamManipulation/Type. I think we just need a little extra logic in `Member` to both detect these as lists (maybe in `.max_occurs`) and also extract the nested type for further processing (e.g. enum generation). These `Type` attributes are optional so they might not appear in a given document, but I think we should normalize that to an empty list in our model classes rather than make it `Optional`. `xmlschema` `to_dict` does return a list of strings for an `xsd:list` (if the attribute is present) so we don't need to do anything extra there.

**Comment by tlambert03** [comment]
question:  what is the syntax for an XML _attribute_ that can be a list?
the only OME example I could find was this ... but `xsd:list` suggests that`Experiment` can also have multiple `Type`s, yes?

```xml
    <Experiment ID="Experiment:1" Type="TimeLapse">
        <Description>Cell Embryo</Description>
        <ExperimenterRef ID="Experimenter:1"/>
    </Experiment>
```

**Comment by tlambert03** [comment]
...sorry, stumbled upon the answer myself:  space delimited... eg:

```xml
    <Experiment ID="Experiment:1" Type="TimeLapse SpectralImaging">
        <Description>Cell Embryo</Description>
        <ExperimenterRef ID="Experimenter:1"/>
    </Experiment>
```
