### ISSUE TITLE
issue with Experiment and MicrobeamManipulation "type" fields

### ISSUE THREAD

**Issue by tlambert03** [tlambert03/ome-types#45]
`Experiment/Type` and `MicrobeamManipulation/Type` are not getting rendered correctly.

```python
class MicrobeamManipulation:
    ...
    type = None
```

**Comment by jmuhlich** [comment]
This is the same root issue as #35 right?

**Comment by tlambert03** [comment]
ah, yep. sorry, it's a duplicate.  I have a working start on i (but it breaks round tripping for the moment) ...  will submit shortly
