### ISSUE TITLE
Pluralize container attributes

### ISSUE THREAD

**Issue by tlambert03** [tlambert03/ome-types#5]
`object.image` (and similar containers) should be accessible at `object.images` ... probably as an alias, so as to remain consistent with the OME model

**Comment by jmuhlich** [comment]
I could support fully renaming the containers to their plural form. Consider it part of the pythonization of the element names -- I think it's only a small step beyond converting CamelCase to snake_case.

**Comment by jmuhlich** [comment]
The "xsd-fu" custom annotations in the schema provide plural forms for all elements which we should extract.

**Comment by jmuhlich** [comment]
I'm almost done with this. What do you think about adding the plurals as an alias (or making the original singulars the alias) vs. dropping the singulars entirely?

**Comment by tlambert03** [comment]
i'm ok with dropping the singulars entirely.  easy to add them back as aliases in the future if we change our minds

**Comment by jmuhlich** [comment]
Implemented in #22
