### ISSUE TITLE
Add support for already in memory XML string or etree

### ISSUE THREAD

**Issue by JacksonMaxfield** [tlambert03/ome-types#50]
Thanks @tlambert03 and @jmuhlich for the work on this library we are looking to adopt it into `aicsimageio`.

`from_xml` only accepts a `Path` or a `str` _to a path_, could it also be expanded to support accepting an already in memory XML str, [`xml etree`](https://docs.python.org/3/library/xml.etree.elementtree.html), or, [`lxml etree`](https://lxml.de/tutorial.html#the-elementtree-class).

**Comment by tlambert03** [comment]
it should also accept a raw XML string... (though I think this was recently broken?).  From the current master, I can read from the test xml files:

```python
In [1]: with open('testing/data/single-image.ome.xml') as f:
   ...:     xml = f.read()
   ...:

In [2]: type(xml)
Out[2]: str

In [3]: print(xml)
<?xml version="1.0" encoding="UTF-8"?>
<OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-06"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-06
                         http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd">
  <Image ID="Image:0" Name="6x6x1x8-swatch.tif">
    <AcquisitionDate>2010-02-23T12:51:30</AcquisitionDate>
    <Pixels DimensionOrder="XYCZT" ID="Pixels:0:0" PhysicalSizeX="10000.0"
            PhysicalSizeY="10000.0" Type="uint8" SizeC="1" SizeT="1" SizeX="6" SizeY="4" SizeZ="1">
      <Channel Color="-2147483648" ID="Channel:0"/>
      <BinData BigEndian="false" Length="32"
                   >/wCrzur//wB5oMPi/wBIbJO3AP8ePGCF</BinData>
    </Pixels>
  </Image>
</OME>

In [4]: from ome_types import from_xml

In [5]: from_xml(xml)
Out[5]: OME(images=[<1 Images>])
```

not working for you?

**Comment by jmuhlich** [comment]
And we should be able to accept an xml or lxml `ElementTree` with a little refactoring (the xmlschema package we use can already parse directly from an `ElementTree` in addition to a path or source-string).

**Comment by jmuhlich** [comment]
@JacksonMaxfield on that note, I've been debating writing a standalone OME-TIFF read/write library that doesn't use tifffile at all and integrates well with `ome_types`. Would you guys be interested in that?

**Comment by tlambert03** [comment]
I definitely want _some_ sort of tiff read/write integration here (see #51) ... so I'm definitely interested in that.  What's your motivation for not using `tifffile` at all?

**Comment by JacksonMaxfield** [comment]
Oh sorry I didn't realize that the `os.fspath` ignore `str` or bytes-like when I was digging through the code. I see on #51 that you are adding a docstring so this can be closed with that probably!

Responding to the read/write library without tifffile, right now, not too sure. For us, since we are already extracting the metadata from tifffile / aicspylibczi / w.e. reader, there isn't _too_ much value in having a "non-image-loading metadata creator". Not yet anyway. (I will say though it sounds cool)

**Comment by jmuhlich** [comment]
Ah, it *would* read/write image data, just not through tifffile. Our group has been dying for TIFF library that would let us A: read individual tiles by position, B: write tile-by-tile without needing to allocate and pass the entire image array up front, C: do both of those on SubIFDs to support the new OME-TIFF pyramid spec (and of course D: provide OME metadata support). tifffile didn't have those features at the beginning of this year, but now that I look again it seems that Gohlke has been chipping away at them over the summer. I'll have to re-evaluate it.

**Comment by JacksonMaxfield** [comment]
Ahhh I see. Yea, we have been monitoring Gohlke's work on it to add those features and in general we think we can come up with a way to wrap his API w/ our dask stuff to make writing plane-by-plane / pyramidal level-by-level possible. So a combination of stuff I think is our current solution to this problem.

**Comment by JacksonMaxfield** [comment]
Back with an update as I am _finally_ starting this work.

Not working for me unfortunately:
```python
In [1]: from tifffile import TiffFile

In [2]: from ome_types import from_xml

In [3]: with TiffFile("aicsimageio/tests/resources/s_1_t_1_c_1_z_1.ome.tiff") as tiff:
   ...:     ome = from_xml(tiff.ome_metadata)
   ...: 
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-200f9f568ea4> in <module>
      1 with TiffFile("aicsimageio/tests/resources/s_1_t_1_c_1_z_1.ome.tiff") as tiff:
----> 2     ome = from_xml(tiff.ome_metadata)
      3 

~/miniconda3/envs/aicsimageio/lib/python3.8/site-packages/ome_types/__init__.py in from_xml(xml)
     35     """
     36     xml = os.fspath(xml)
---> 37     d = to_dict(xml)
     38     for key in list(d.keys()):
     39         if key.startswith(("xml", "xsi")):

~/miniconda3/envs/aicsimageio/lib/python3.8/site-packages/ome_types/schema.py in to_dict(xml, schema, converter, **kwargs)
    260         if annotation["_type"] == "xml_annotation":
    261             if tree is None:
--> 262                 tree = ElementTree.parse(xml)
    263             aid = annotation["id"]
    264             elt = tree.find(f".//{NS_OME}XMLAnnotation[@ID='{aid}']/{NS_OME}Value")

~/miniconda3/envs/aicsimageio/lib/python3.8/xml/etree/ElementTree.py in parse(source, parser)
   1200     """
   1201     tree = ElementTree()
-> 1202     tree.parse(source, parser)
   1203     return tree
   1204 

~/miniconda3/envs/aicsimageio/lib/python3.8/xml/etree/ElementTree.py in parse(self, source, parser)
    582         close_source = False
    583         if not hasattr(source, "read"):
--> 584             source = open(source, "rb")
    585             close_source = True
    586         try:

OSError: [Errno 36] File name too long: '<?xml version="1.0" encoding="UTF-8"?>
```

I cut off the full error because it just prints out the entire XML string.

Also tried with `from_tiff` but results in the same error.

But since you have tests for `from_tiff` it makes me think this a problem with _my file_... :thinking: 
My test file can be downloaded [here](https://open.quiltdata.com/b/aics-modeling-packages-test-resources/tree/aicsimageio/test_resources/resources/s_1_t_1_c_1_z_1.ome.tiff)

**Comment by tlambert03** [comment]
actually, looks like this is our error... in the `ElementTree.parse()` call in `ome_types.schema.to_dict`:
https://github.com/tlambert03/ome-types/blob/a812abb731ab5100001d09db36c08d9cae9bc47c/src/ome_types/schema.py#L259-L262
whereas the function 
`ElementTree.parse` requires that `xml` be a filename or file object... but the `to_dict` function also accepts a string... I can post a fix shortly

**Comment by JacksonMaxfield** [comment]
Also question on how this works in general. When I use `from_xml` does it _always_ make an http request to validate the schema?

**Comment by tlambert03** [comment]
> When I use from_xml does it always make an http request to validate the schema?

as long as the schema namespace is `"http://www.openmicroscopy.org/Schemas/OME/2016-06"` (as yours is), then it will not incur a request.  The relevant code is here:

https://github.com/tlambert03/ome-types/blob/a812abb731ab5100001d09db36c08d9cae9bc47c/src/ome_types/schema.py#L34-L40

otherwise, it will incur a request (but a lot of other stuff is expected to break at that point since we decided a while back to just focus on OME-2016-06 for now... )

**Comment by tlambert03** [comment]
i think the original purpose of this issue was addressed.  Closing but feel free to reopen or start a new one with more
