### ISSUE TITLE
Add CRON to build infra to catch dependency breakages

### ISSUE THREAD

**Issue by JacksonMaxfield** [tlambert03/ome-types#78]
`xmlschema` released a new version (1.5.0) on Friday (5 Feb 2021) that moved around some of the objects / functions in the library.

```python
c:\users\dmt\anaconda3\envs\aicsimageio\lib\site-packages\ome_types\__init__.py:18: in <module>
    from .schema import to_dict, to_xml, validate  # isort:skip
c:\users\dmt\anaconda3\envs\aicsimageio\lib\site-packages\ome_types\schema.py:13: in <module>
    from xmlschema.converters import ElementData, XMLSchemaConverter
E   ImportError: cannot import name 'ElementData' from 'xmlschema.converters' (c:\users\dmt\anaconda3\envs\aicsimageio\lib\site-packages\xmlschema\converters\__init__.py)
```

This is just to alert that any sort of build systems that install `ome-types` (and `xmlschema` as a dependency) will likely fail today :)

@tlambert03 I will make a PR to resolve this later today probably. Alright if I also in that PR include a change to the `build` GitHub workflow to add a CRON job for this?

We have CRON jobs on `aicsimageio` build for these types of dependency catching: [example](https://github.com/AllenCellModeling/aicsimageio/blob/main/.github/workflows/build-main.yml#L8)

**Comment by tlambert03** [comment]
thanks @JacksonMaxfield, yeah, it's been difficult to keep the xmlschema stuff working.  Even 1.4.2 broke some of the autogeneration stuff... and we need >= 1.4.1 for the serialization stuff.  So in master, at the moment, we're already [pinned at 1.4.1](https://github.com/tlambert03/ome-types/blob/cd15bcab83cc73c96c243943d41729a570b3b377/setup.cfg#L31).  (but that hasn't been released to pypi yet)

> @tlambert03 I will make a PR to resolve this later today probably. Alright if I also in that PR include a change to the build GitHub workflow to add a CRON job for this?

anything you can/want to do is greatly appreciated!  We have similar cron tests at napari and I'm all for it

**Comment by JacksonMaxfield** [comment]
Hmmm yea I will treat this issue primarily as just "add a CRON to check when dependencies break the install" but could we get a pypi release out to resolve CI build issues?

**Comment by tlambert03** [comment]
> Hmmm yea I will treat this issue primarily as just "add a CRON to check when dependencies break the install" but could we get a pypi release out to resolve CI build issues?

Will do today.  Thanks!
