### ISSUE TITLE
BinData can't be instantiated

### ISSUE THREAD

**Issue by jmuhlich** [tlambert03/ome-types#9]
I don't think dataclasses can usefully subclass a non-dataclass or really any non-cooperative class. For example our `BinData` ultimately subclasses `str` and I discovered there's no way to actually instantiate one due to errors from either the `str` constructor or the pydantic validator. How would the core string value actually get passed in here, anyway? The other subclasses of `ConstrainedStr` seem OK since they aren't also dataclasses. Maybe BinData should be a top-level class with an attribute `value: base64Binary` rather than inheriting.

**Comment by jmuhlich** [comment]
Simply making that proposed change (moving the content to a `value` attribute) makes 14/32 of the example files at https://github.com/ome/ome-model/tree/master/specification/samples/2016-06 parse without error. I didn't inspect them all to see if the returned object looks correctly structured, but it's a good start. I'll look into how to make that change in `OVERRIDE`.

**Comment by tlambert03** [comment]
yeah I recall some of the constrained strings (with additional properties) being hard to model... but I didn't appreciate that it couldn't even be instantiated!  That'll never do! :)
how many of those files are parsing without error before that fix?  (we should update the tests here to use those)

**Comment by jmuhlich** [comment]
Zero!

**Comment by tlambert03** [comment]
fwiw, I'm more than happy to use whatever "ugliness" is necessary for now to just get the output model working.  So if using the current `OVERRIDE` pattern is not working, and you want to just put a conditional somewhere in the body of the code with a "`# FIXME:`" or something like that.  That's fine with me and we can refactor later
