### ISSUE TITLE
Issues with tiff-files exported from NIS elements using Export ND to Tiff 

### ISSUE THREAD

**Issue by VolkerH** [tlambert03/ome-types#98]
Below is a link to a sample file exported from NIS elements using the following dialog

![image](https://user-images.githubusercontent.com/2210044/125746703-a5178490-efd5-4877-8328-c7fca0c61652.png)

https://www.dropbox.com/s/qiikd154xy4d9xx/seq0000xy01c1.tif?dl=0

I have been extracting metadata from this file using code in the following (messy) notebook (under the last heading):
https://github.com/VolkerH/PythonSnippets/blob/master/metadata_tifffile/tifffile%20metatada%20experiments.ipynb

I just tried this with `ome_types`. 

If I try 

```
from_tiff("seq0000xy01c1.tif")
```
I get a unicode error:
```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-11-52cd54144d4d> in <module>
----> 1 from_tiff("/home/hilsenst/Desktop/seq0000xy01c1.tif")

~/miniconda3/envs/napari_latest/lib/python3.9/site-packages/ome_types/_convenience.py in from_tiff(path)
     50         If the TIFF file has no OME metadata.
     51     """
---> 52     return from_xml(_tiff2xml(path))
     53 
     54 

~/miniconda3/envs/napari_latest/lib/python3.9/site-packages/ome_types/_convenience.py in _tiff2xml(path)
    102     if desc[-1] == 0:
    103         desc = desc[:-1]
--> 104     return desc.decode("utf-8")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 1746: invalid start byte
```

When I extract the XML string using tifffile as in my notebook and pass it to `from_xml` I get the following error which is potentially related to #86.

```
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-13-0e209f70ab29> in <module>
----> 1 from_xml(nd2totiff.ome_metadata)

~/miniconda3/envs/napari_latest/lib/python3.9/site-packages/ome_types/_convenience.py in from_xml(xml)
     27             d.pop(key)
     28 
---> 29     return OME(**d)  # type: ignore
     30 
     31 

~/miniconda3/envs/napari_latest/lib/python3.9/site-packages/ome_types/model/ome.py in __init__(self, **data)
    135 
    136     def __init__(self, **data: Any) -> None:
--> 137         super().__init__(**data)
    138         self._link_refs()
    139 

~/miniconda3/envs/napari_latest/lib/python3.9/site-packages/ome_types/_base_type.py in __init__(__pydantic_self__, **data)
     78         if "id" in __pydantic_self__.__fields__:
     79             data.setdefault("id", OMEType._AUTO_SEQUENCE)
---> 80         super().__init__(**data)
     81 
     82     # pydantic BaseModel configuration.

~/miniconda3/envs/napari_latest/lib/python3.9/site-packages/pydantic/main.cpython-39-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for OME
images -> 0 -> acquisition_date
  invalid datetime format (type=value_error.datetime)
```

**Comment by jmuhlich** [comment]
Your sample file uses the older 2015-01 OME-XML schema but ome-types only handles the latest 2016-06 schema. BioFormats provides a mechanism to convert older to newer but we didn't incorporate it into ome-types yet. A quick fix is to use `bfconvert` from BioFormats to convert to `.ome.tif` as that will perform the schema upgrade automatically:

```shell
bfconvert oldfile.tif newfile.ome.tif
```

**Comment by joaomamede** [comment]
bfconvert can also convert from the .nd2 you might save some time if you do so.

**Comment by tlambert03** [comment]
going to close this since we don't directly support 2015-01 OME-XML

**Comment by tlambert03** [comment]
yeah, I'm interested in implementing that... can you point me to the actual xsl transformations that OME uses?  i couldn't easily find them

**Comment by jmuhlich** [comment]
https://github.com/ome/ome-model/tree/fbe39c099b4b3ab02ccfa93c0af6bcf84515a564/specification/src/main/resources/transforms

**Comment by tlambert03** [comment]
thanks!

**Comment by jmuhlich** [comment]
Good grief when do you sleep???!!? Awesome work!
